### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub/iohub#1]
After migrating the `io` module of `waveorder` (at https://github.com/mehta-lab/waveorder/commit/5f60f0ad27e05596a6f6cb09ef2310f6bc00f236) to this new repository, the next steps may include:

- [x] Reach a consensus on the scope and modulation of this project and draft the README and CONTRIBUTION documents accordingly. #39 #32 #36 
- [x] Fix references and the directory structure so that the existing features work and the tests pass. #4 #46
- [ ] Discuss and implement the abstraction that suites the need of our users (e.g. an `iohub.Dataset` class that offer an array-like interface), and make sure the existing feature set works under it. #31 #40 #132
- [x] Package the library and publish on PyPI so other packages can depend on it. #55
- [ ] Expand the readers and writers to support more data formats. #99 #114

Where each of these can be elaborated/debated upon in spin-off issues

@mattersoflight @JoOkuma @royerloic @talonchandler @Christianfoley please feel free to add to or modify these objectives.
